### ISSUE TITLE
State outside actor. Concurrency issue?

### ISSUE THREAD

**Issue by KonstantinBerkow** [manuelvicnt/MathCoroutines#1]
Hi, stumbled across your article. Nice comparison of rx with coroutines.
But something bugs me. Is it safe to change value of `askForFunFact` (in `MainViewModel`) from coroutine? Next time it can be invoked on another thread and read wrong value. I think it would be better moved inside actor and passed as parameter to `processCalculation ` like this:

```
val userActionActor = actor<MainUserAction>(CommonPool, parent = parentJob) {
    var askForFunFact = false
    for (msg in channel) {
        when (msg) {
            is MainUserAction.Calculate -> {
                if (msg.number <= 0) {
                    viewStateChannel.offer(MainViewState.WrongInputError)
                } else {
                    viewStateChannel.offer(MainViewState.Loading)
                    processCalculation(msg, askForFunFact)
                }
            }
            is MainUserAction.FunFactEnabled -> {
                askForFunFact = msg.enabled
            }
        }
    }
}
```

What do you think?

**Comment by manuelvicnt** [comment]
Hi @KonstantinBerkow ! Thanks for commenting. It's true that it's not thread safe and could be modified by other threads. In the current code, I don't think there is any threading issue since it's just the actor modifying the variable. The code inside the actor is executed sequentially and just one event at a time. We'd be in trouble if other parts of the code modify that variable. 

However, **moving the variable to the actor scope is a good idea** to avoid problems in the future :)
Thanks for taking the time to comment.
